apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom
spec:
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
      - name: node-exporter
        image: bitnami/node-exporter
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9100


---
apiVersion: v1
kind: Service
metadata:
  name: prom
spec:
  type: NodePort
  selector:
    app: prom
  ports:
  - port: 9100
    targetPort: 9100
    nodePort: 30001
