apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capestone-application
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/abdulfrfr/hostspace_capestone.git'
    path: capestone-chart
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
