apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: "2024-03-23T12:40:58Z"
  name: mongosecret
  namespace: default
  resourceVersion: "29377"
  uid: d0014d26-d3d4-41ce-8e6d-879e22b735ca
type: Opaque
