---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBzJcXsHKjoiL3Uiu0k0NFTOrbxXycaXrwwNaZx8nhVv1IZCJEO6ysXwWsuvBXcesMIea4SwujQ9260ilr+0a5vyAn8AtsaeGFdPtbBbu7E7O1J4cFV3HTqx01AQfojDLPR7xd3DTN3WT9wX07iGvpEEulsdxt+6NmGeeSh9MrFd14lwdB7cHxm85h5B2cCyw2OqInZt2Ftv1L+rnFCdlbQ2gm5aI6gUNB1QAX2C1B46oxAaIqjEMinlR2SZS3yOyZO+/vlLAHct45SPcaKKpmO1TfMix8JqTve2Fm69PzeLz/zC+5ksNIHF9I+ZbV+R1mPDq63xSDpOFf/COwpKX4BcYq5GYseHYBj0qc/YUx4M7LiXo13epxIWXKRiOR8vZo2bIlOngMHgen8Ij22PITpMxipuDvzNb2aylC0S+kSZ15/jwtkNtiyl0OyE/ywqrHI581sx2DQUi3KZQc3j6Ps83XbZEKb+p/l1oQHau2bk6K15j0oL0S67MGKWkaZk16xD11gB5Sq8M8lqk2nwtQx74KKCHkhoijhxlmQ6qozEEslM/opBR3KQINYFwvvFg/4b9fvG3ybjeDAphoTRfHgPobidEMS18YjnfMPjVy2RbZmrEI8KzIpVjAOYpt9ymmrCCVcuBTWcrqk1lgE+fLcua8ZDnNGWYvS910fPnUOLE3Wfxeax4ALAawn48chtZi+GG+Hfo9ghVYDayw=
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: default
    type: Opaque
