# frontend application's values
frontend:
  replicas: 1
  containers:
    image: ""
    name: frontend
    port: 80
    resources:
      limits:
          cpu: 500m
          memory: 512Mi
      requests:
          cpu: 250m
          memory: 256Mi
    imagePullPolicy: always
    env:
      name1: REACT_APP_BACKEND_URL
      value1: ""


# backend application's values
backend:
  replicas: 1
  containers:
    image: ""
    name: frontend
    port: 80
    resources:
      limits:
          cpu: 500m
          memory: 512Mi
      requests:
          cpu: 250m
          memory: 256Mi
    imagePullPolicy: always
    env:
      name1: MONGODB_URL
      value1: ""
      name2: PORT
      value2: ""


# db application's values
db:
  replicas: 1
  containers:
    image: mongo-express
    name: db
    port: 27017
    resources:
      limits:
          cpu: 500m
          memory: 512Mi
      requests:
          cpu: 250m
          memory: 256Mi
    imagePullPolicy: always

# frontend service's values
service:
  frontend:
    type: LoadBalancer
    nodePort: 30000
    targetPort: 80
    port: 80
  backend:
    type: ClusterIP
    nodePort: 30001
    targetPort: 5000
    port: 5000
  db:
    type: ClusterIP
    targetPort: 27017
    port: 27017