# frontend application's values
frontend:
  replicas: 1
  containers:
    image: docker.io/abdulfrfr/frontend-app:latest
    name: frontend
    port: 80
    resources:
      limits:
          cpu: 500m
          memory: 512Mi
      requests:
          cpu: 250m
          memory: 256Mi
    imagePullPolicy: Always
    env:
      name1: REACT_APP_BACKEND_URL
      value1: 192.168.49.2:30001/data


# backend application's values
backend:
  replicas: 1
  containers:
    image: docker.io/abdulfrfr/backend-app:latest
    name: backend
    port: 5000
    resources:
      limits:
          cpu: 500m
          memory: 512Mi
      requests:
          cpu: 250m
          memory: 256Mi
    imagePullPolicy: Always
    env:
      name1: MONGODB_URL
      name2: PORT


# db application's values
db:
  replicas: 1
  containers:
    image: mongo:latest
    name: db
    port: 27017
    resources:
      limits:
          cpu: 500m
          memory: 512Mi
      requests:
          cpu: 250m
          memory: 256Mi
    imagePullPolicy: Always

# frontend service's values
service:
  frontend:
    type: ClusterIP
    nodePort: 30000
    targetPort: 80
    port: 80
  backend:
    type: ClusterIP
    nodePort: 30001
    targetPort: 5000
    port: 80
  db:
    type: ClusterIP
    targetPort: 27017
    port: 27017