apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-backend-deploy
    labels:
        app: backend-app
spec:
    replicas: {{ .Values.backend.replicas }}
    selector:
        matchLabels:
            app: backend-app
    template:
        metadata:
            labels:
                app: backend-app
        spec:
            containers:
                - image: {{ .Values.backend.containers.image }}
                  name: {{ .Values.backend.containers.name }}
                  ports:
                   - containerPort: {{ .Values.backend.containers.port }}
                  resources:
                    limits:
                        cpu: {{ .Values.backend.containers.resources.limits.cpu }}
                        memory: {{ .Values.backend.containers.resources.limits.memory }}
                    requests:
                        cpu: {{ .Values.backend.containers.resources.requests.cpu }}
                        memory: {{ .Values.backend.containers.resources.requests.memory }}
                  imagePullPolicy: {{ .Values.backend.containers.imagePullPolicy }}
                  env:
                    -   name: MONGO_URL
                        value: db-svc
                    -   name: MONGO_NS
                        value: default
                    -   name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Release.Name }}-configmap
                                key: MONGO_INITDB_ROOT_USERNAME
                    -   name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: capestone
                                key: MONGO_INITDB_ROOT_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    type: {{ .Values.service.backend.type }}
    selector:
        app: backend-app
    ports:
     - name: http
       protocol: TCP
       targetPort: {{ .Values.service.backend.targetPort }}
       port: {{ .Values.service.backend.port }}
{{- if eq .Values.service.backend.type "NodePort" }}
       nodePort: {{ .Values.service.backend.nodePort }}
{{ end -}}