apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-db-deploy
    labels:
        app: db-app
spec:
    replicas: {{ .Values.db.replicas }}
    selector:
        matchLabels:
            app: db-app
    template:
        metadata:
            labels:
                app: db-app
        spec:
            containers:
                - image: {{ .Values.db.containers.image }}
                  name: {{ .Values.db.containers.name }}
                  ports:
                    - containerPort: {{ .Values.db.containers.port }}
                  resources:
                    limits:
                        cpu: {{ .Values.db.containers.resources.limits.cpu }}
                        memory: {{ .Values.db.containers.resources.limits.memory }}
                    requests:
                        cpu: {{ .Values.db.containers.resources.requests.cpu }}
                        memory: {{ .Values.db.containers.resources.requests.memory }}
                  imagePullPolicy: {{ .Values.db.containers.imagePullPolicy }}
                  env:
                    -  name: MONGO_INITDB_ROOT_USERNAME
                       valueFrom:
                            configMapKeyRef:
                                name: {{ .Release.Name }}-configmap
                                key: MONGO_INITDB_ROOT_USERNAME
                    -  name: MONGO_INITDB_ROOT_PASSWORD
                       valueFrom:
                            secretKeyRef:
                                name: secret
                                key: MONGO_INITDB_ROOT_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
    name: db-svc
spec:
    type: {{ .Values.service.db.type }}
    selector:
        app: db-app
    ports:
        - name: http
          port: {{ .Values.service.db.port }}
          protocol: TCP
          targetPort: {{ .Values.service.db.targetPort }}