apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-frontend-deploy
    labels:
        app: frontend-app
spec:
    replicas: {{ .Values.frontend.replicas }}
    selector:
        matchLabels:
            app: frontend-app
    template:
        metadata:
            labels:
                app: frontend-app
        spec:
            containers:
                - image: {{ .Values.frontend.containers.image }}
                  name: {{ .Values.frontend.containers.name }}
                  ports:
                   - containerPort: {{ .Values.frontend.containers.port }}
                  resources:
                    limits:
                        cpu: {{ .Values.frontend.containers.resources.limits.cpu }}
                        memory: {{ .Values.frontend.containers.resources.limits.memory }}
                    requests:
                        cpu: {{ .Values.frontend.containers.resources.requests.cpu }}
                        memory: {{ .Values.frontend.containers.resources.requests.memory }}
                  imagePullPolicy: {{ .Values.frontend.containers.imagePullPolicy }}
                  env:
                    - name: BACKEND_URL
                      value: http://192.168.49.2:30001/


                  
---

apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-frontend-svc
spec:
    type: {{ .Values.service.frontend.type }}
    selector:
        app: frontend-app
    ports:
     - name: http
       protocol: TCP
       targetPort: {{ .Values.service.frontend.targetPort }}
       port: {{ .Values.service.frontend.port }}
{{- if eq .Values.service.frontend.type "NodePort" }}
       nodePort: {{ .Values.service.frontend.nodePort }}
{{ end -}}